// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAqW5yVcXRYZiyCHe1LTocI_6SOLZa0Hk',
    appId: '1:276114206636:ios:76c94cb006b7cf02685409',
    messagingSenderId: '276114206636',
    projectId: 'cryptofx-4921b',
    storageBucket: 'cryptofx-4921b.firebasestorage.app',
    iosBundleId: 'com.example.cryptofx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAqW5yVcXRYZiyCHe1LTocI_6SOLZa0Hk',
    appId: '1:276114206636:ios:76c94cb006b7cf02685409',
    messagingSenderId: '276114206636',
    projectId: 'cryptofx-4921b',
    storageBucket: 'cryptofx-4921b.firebasestorage.app',
    iosBundleId: 'com.example.cryptofx',
  );

  /// Config Web (Chrome, Edge) — même projet que Windows.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMqBkmf9u-oF2XglgTcShFq11yeKVVuEM',
    appId: '1:276114206636:web:4df6d1a0b7296a61685409',
    messagingSenderId: '276114206636',
    projectId: 'cryptofx-4921b',
    authDomain: 'cryptofx-4921b.firebaseapp.com',
    storageBucket: 'cryptofx-4921b.firebasestorage.app',
    measurementId: 'G-B2FTFY0EXC',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMqBkmf9u-oF2XglgTcShFq11yeKVVuEM',
    appId: '1:276114206636:web:4df6d1a0b7296a61685409',
    messagingSenderId: '276114206636',
    projectId: 'cryptofx-4921b',
    authDomain: 'cryptofx-4921b.firebaseapp.com',
    storageBucket: 'cryptofx-4921b.firebasestorage.app',
    measurementId: 'G-B2FTFY0EXC',
  );
}
